[package]
name = "sqlite_test"
version = "0.1.0"
authors = ["ta32 <ir.ta.work@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = {version = "^0", features = ["bundled"]}